### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by zvictor** [koyeb/pulumi-koyeb#15]
> For detailed reference documentation, please visit [the Pulumi registry](https://www.pulumi.com/registry/packages/koyeb/api-docs/).

This link in the README (last line) is broken 😢

**Comment by edouardb** [comment]
Hi @zvictor,

Thanks for reporting this! The Koyeb Pulumi provider is not yet published in the Pulumi registry, this is why you can't access this page. We plan to list it in the next few weeks.
